version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://zephy:password@db:5432/zephyjr
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production
      - ADMIN_EMAIL=admin@zephyjr.com
      - ADMIN_PASSWORD=admin123
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
    volumes:
      - ./backend:/app
      - ./Chatbot_old.py:/app/Chatbot_old.py
      - ./client_secrets:/app/client_secrets
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - zephy-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - zephy-network

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=zephyjr
      - POSTGRES_USER=zephy
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - zephy-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - zephy-network

volumes:
  postgres_data:
  redis_data:

networks:
  zephy-network:
    driver: bridge